# SPDX-License-Identifier: CDDL-1.0
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# This run file contains all of the common functional tests.  When
# adding a new test consider also adding it to the sanity.run file
# if the new test runs to completion in only a few seconds.
#
# Approximate run time: 4-5 hours
#

[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 600
post_user = root
post = cleanup
failsafe_user = root
failsafe = callbacks/zfs_failsafe
tags = ['functional']

[tests/functional/rsend]
tests = ['recv_dedup', 'recv_dedup_encrypted_zvol',
    'rsend_003_pos', 'rsend_004_pos', 'rsend_005_pos',
    'rsend_006_pos', 'rsend_007_pos', 'rsend_008_pos', 'rsend_009_pos',
    'rsend_010_pos', 'rsend_011_pos', 'rsend_012_pos', 'rsend_013_pos',
    'rsend_014_pos', 'rsend_016_neg', 'rsend_019_pos', 'rsend_020_pos',
    'rsend_021_pos', 'rsend_022_pos', 'rsend_024_pos', 'rsend_025_pos',
    'rsend_026_neg', 'rsend_027_pos', 'rsend_028_neg', 'rsend_029_neg',
    'rsend_030_pos', 'rsend_031_pos', 'send-c_verify_ratio',
    'send-c_verify_contents', 'send-c_props', 'send-c_incremental',
    'send-c_volume', 'send-c_zstream_recompress', 'send-c_zstreamdump',
    'send-c_lz4_disabled', 'send-c_recv_lz4_disabled',
    'send-c_mixed_compression', 'send-c_stream_size_estimate',
    'send-c_embedded_blocks', 'send-c_resume', 'send-cpL_varied_recsize',
    'send-c_recv_dedup', 'send-L_toggle', 'send_encrypted_incremental',
    'send_encrypted_freeobjects', 'send_encrypted_hierarchy',
    'send_encrypted_props', 'send_encrypted_truncated_files',
    'send_freeobjects', 'send_realloc_files', 'send_realloc_encrypted_files',
    'send_spill_block', 'send_holds', 'send_hole_birth', 'send_mixed_raw',
    'send-wR_encrypted_zvol', 'send_partial_dataset', 'send_invalid',
    'send_doall', 'send_raw_spill_block', 'send_raw_ashift',
    'send_raw_large_blocks', 'send_leak_keymaps']
tags = ['functional', 'rsend']
